### ISSUE TITLE
f.slice is not a function

### ISSUE THREAD

**Issue by laodemalfatih** [mgcrea/node-xlsx#110]
I tried to read an excel file that doesn't have extension, and i get error below.I don't know if this library doesn't support reading excel files that don't have extensions. But certainly when I try to open the same file in **LibreCalc**, I don't get a problem.

```
TypeError: f.slice is not a function
    at firstbyte (/home/lod/Documents/Projects/NodeJS/d1-excel-reader/node_modules/xlsx/xlsx.js:20226:38)
    at Object.readSync [as read] (/home/lod/Documents/Projects/NodeJS/d1-excel-reader/node_modules/xlsx/xlsx.js:20308:14)
    at Object.parse (/home/lod/Documents/Projects/NodeJS/d1-excel-reader/node_modules/node-xlsx/lib/index.js:31:86)
    at exports.post./ (/home/lod/Documents/Projects/NodeJS/d1-excel-reader/controller/api/upload.js:11:39)
    at Layer.handle [as handle_request] (/home/lod/Documents/Projects/NodeJS/d1-excel-reader/node_modules/express/lib/router/layer.js:95:5)
    at next (/home/lod/Documents/Projects/NodeJS/d1-excel-reader/node_modules/express/lib/router/route.js:137:13)
    at /home/lod/Documents/Projects/NodeJS/d1-excel-reader/lib/upload/lib/filter.js:120:4
    at Layer.handle [as handle_request] (/home/lod/Documents/Projects/NodeJS/d1-excel-reader/node_modules/express/lib/router/layer.js:95:5)
    at next (/home/lod/Documents/Projects/NodeJS/d1-excel-reader/node_modules/express/lib/router/route.js:137:13)
    at IncomingForm.<anonymous> (/home/lod/Documents/Projects/NodeJS/d1-excel-reader/lib/upload/lib/upload.js:188:6)
    at IncomingForm.emit (events.js:182:13)
    at IncomingForm._maybeEnd (/home/lod/Documents/Projects/NodeJS/d1-excel-reader/lib/upload/node_modules/formidable/lib/incoming_form.js:557:8)
    at /home/lod/Documents/Projects/NodeJS/d1-excel-reader/lib/upload/node_modules/formidable/lib/incoming_form.js:238:12
    at WriteStream.<anonymous> (/home/lod/Documents/Projects/NodeJS/d1-excel-reader/lib/upload/node_modules/formidable/lib/file.js:79:5)
    at Object.onceWrapper (events.js:273:13)
    at WriteStream.emit (events.js:182:13)
```

**Comment by crecreek** [comment]
same question

**Comment by TatiTheFreaK** [comment]
If you are using multer to upload the file, you need to use
`const sheet = XLSX.read(req.file.buffer);`

**Comment by Eduwardo** [comment]
Since we are talking about [node-xlsx](https://github.com/mgcrea/node-xlsx) package, not [SheetJS](https://github.com/SheetJS/sheetjs), you should use: 

 ```js
import xlsx from 'node-xlsx';

const sheet = xlsx.parse(req.file.buffer);
```

**Comment by ewertonrfd** [comment]
Se tiverem usando AdonisJS 6

Pode fazer assim

`public async import({ request, response }: HttpContext) {
    const { file } = await request.validateUsing(importFileValidator);

    if (!file || !file.tmpPath) {
      return response.badRequest({
        message: "File not found",
      });
    }
        
    const fileBuffer = fs.readFileSync(file.tmpPath);
    const workbook = xlsx.read(fileBuffer);
    const sheetName = workbook.SheetNames[0];
    const sheet = workbook.Sheets[sheetName];
    const data = xlsx.utils.sheet_to_json(sheet);`
