### ISSUE TITLE
TypeError:Cannot set  property length of [Object Object] which has only a getter

### ISSUE THREAD

**Issue by xmlee** [mgcrea/node-xlsx#31]
I used it to parse xls successfully.
however when I use it to parse xls documents  again,it shows the message.
TypeError:Cannot set  property length of [Object Object] which has only a getter
at dbcs_d (node-xlsx\node_modules\xlsx\dist\cpexcel.js:989:20)
at Object.decode (node-xlsx\node_modules\xlsx\dist\cpexcel.js:1197:40)
at _gc2 (node-xlsx\node_modules\xlsx\xlsx.js:28:24)
at Buffer.ReadShift [as read_shift] (node-xlsx\node_modules\xlsx\xlsx.js:1623:13)
at parse_ShortXLUnicodeString (node-xlsx\node_modules\xlsx\xlsx.js:3082:21)
at Object.parse_Font [as f] (node-xlsx\node_modules\xlsx\xlsx.js:3470:13)
at slurp (node-xlsx\node_modules\xlsx\xlsx.js:9229:11)
at parse_workbook (node-xlsx\node_modules\xlsx\xlsx.js:9350:15)
at parse_xlscfb (node-xlsx\node_modules\xlsx\xlsx.js:9827:27)
at Object.readSync [as read] (node-xlsx\node_modules\xlsx\xlsx.js:11391:11)

**Comment by mgcrea** [comment]
maybe you're parsing an old .xls file and not a .xlsx?

**Comment by clizSec** [comment]
The same issue happens to me. I am able to parse ```XLS``` files using the library, but I have a specific one that is corrupted, but Office Excel still can open it and show the content and the library displays the same error as in this thread.

**Sample file**: https://filebin.net/487s7quw1bgxqjj1
