### ISSUE TITLE
TypeError: Object function Object() { [native code] } has no method 'assign'

### ISSUE THREAD

**Issue by ifmos** [mgcrea/node-xlsx#48]
It's wonderful to use your tool on Windows10! But today I got a TypeError when using centos7 with nodejs, this is the ErrorCode below. I hope you can fix it :) Thanks!
`at Object.build (/root/projects/czg/node_modules/node-xlsx/lib/index.js:46:57)
    at repl:1:19
    at REPLServer.self.eval (repl.js:110:21)
    at repl.js:249:20
    at REPLServer.self.eval (repl.js:122:7)
    at Interface.<anonymous> (repl.js:239:12)
    at Interface.emit (events.js:95:17)
    at Interface._onLine (readline.js:203:10)
    at Interface._line (readline.js:532:8)
    at Interface._ttyWrite (readline.js:761:14)
`

**Comment by jimmywarting** [comment]
Update your node version...
