### ISSUE TITLE
node-xlsx 0.12 is failing on my node v4.4.4 (and 0.12.1 seems too)

### ISSUE THREAD

**Issue by christopheleroy** [mgcrea/node-xlsx#95]
Hello,

I am stuck with Red Hat 5 for the time being and have to release using node v4.4.4.
When I last installed node-xlsx, the application started to fail open its excel files.

When I downgraded to 0.11.2 everything worked again.
The author, @mgcrea has attempted to fix the situation with 0.12.1 but it has failed for me too.
I'm happy with 0.11.2 -- thank you for all the support!

**Comment by christopheleroy** [comment]
The error manifests itself when opening the excel file, I believe:

..../node/node_modules/node-xlsx/node_modules/xlsx/xlsx.js:2276
        var utf8readc = function utf8readc(data) { return Buffer.from(data, 'binary').toString('utf8'); };
                                                                 ^
    at utf8readc (/..../node/node_modules/node-xlsx/node_modules/xlsx/xlsx.js:2276:59)
    at make_xlsx (...../node/node_modules/node-xlsx/node_modules/xlsx/xlsx.js:2277:25)
TypeError: binary is not a function
    at Function.from (native)
